name: Python CI

on:
  push:
    branches: '**'
  pull_request:
    branches: [main, dev]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest tests/unit

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make scripts executable
        run: chmod +x scripts/start_tf_serving.sh scripts/stop_tf_serving.sh

      - name: Start TensorFlow Serving
        run: ./scripts/start_tf_serving.sh

      - name: Wait for TF Serving to be ready
        run: |
          echo "Waiting for TF Serving to be ready..."
          for i in {1..30}; do
            http_status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8501/v1/models/tomatoes_model || echo "000")
            if [ "$http_status" = "200" ]; then
              echo "TF Serving is ready!"
              exit 0
            fi
            echo "Attempt $i: Server not ready ($http_status). Retrying..."
            sleep 5
          done
          echo "::error::TF Serving did not start within expected time."
          exit 1
      
      - name: check tf serving container logs
        run: |
          docker logs tf_serving_container

      - name: Run integration tests
        run: pytest tests/integration

      - name: Stop TensorFlow Serving
        if: always()
        run: |
          ./scripts/stop_tf_serving.sh
